/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant
    Soft IP Version: 1.0.0
    Mo Jan 21 15:07:43 2019
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pow_pll1 (ref_clk_i, rst_n_i, latch_i, outcore_o, outglobal_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ref_clk_i;
    input  rst_n_i;
    input  latch_i;
    output  outcore_o;
    output  outglobal_o;
endmodule